[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
region = "ap-southeast"
startCommand = "sh ./docker-entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
